# Generated by Django 5.2 on 2026-05-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Banner'), ('about', 'About Us'), ('services', 'Services / Programs'), ('team', 'Our Team'), ('events', 'Upcoming Events'), ('gallery', 'Photo Gallery'), ('testimonials', 'Testimonials'), ('partners', 'Partners & Sponsors'), ('news', 'Latest News / Blog'), ('faq', 'FAQ')], max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Company', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('primary_color', models.CharField(default='#1a56a0', max_length=7)),
                ('secondary_color', models.CharField(default='#f5a623', max_length=7)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('footer_text', models.CharField(blank=True, max_length=200)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
