# Generated by Django 5.2.14 on 2026-05-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nav_events_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='newsletter_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
